# Reads 2002 census common-dwellings population (DBF); outputs data_2002_common.csv

# --- County Reference Table ---
# Load the Stata county-level lookup table (judete.dta) used for county labels and codes
setwd(wd_data_raw)
setwd("./rpl_2002_microdate/")
counties<-read_dta("judete.dta")

# setwd(wd_data_raw)
# setwd("./rpl_2002_microdate/NOM02/")
# activity<-read.dbf("ACTIVITATE02.dbf")

# setwd(wd_data_raw)
# setwd("./rpl_2002_microdate/DOM02/")
# dom<-read.dbf("dom_02.DBF")
#
# setwd(wd_data_raw)
# setwd("./rpl_2002_microdate/LOC02/")
# dom<-read.dbf("loc01_02.dbf")
#
# setwd(wd_data_raw)
# setwd("./rpl_2002_microdate/COMUN02/")
# dom<-read.dbf("comun01_02.dbf")
#
# setwd(wd_data_raw)
# setwd("./rpl_2002_microdate/CLAD02/")
# dom<-read.dbf("clad01_02.dbf")


# --- Citizenship Nomenclature ---
# cet: lookup table mapping citizenship codes to labels (CETATENIE02.DBF from NOM02 folder)
setwd(wd_data_raw)
setwd("./rpl_2002_microdate/NOM02/")
cet<-read.dbf("CETATENIE02.DBF")

# --- SIRUTA Locality Reference Table ---
# siruta_02: official 2002 locality register; provides locality names and administrative hierarchy
setwd(wd_data_raw)
setwd("./rpl_2002_microdate/SIRUTA02/")
siruta_02<-read.dbf("siruta_02.DBF")

#map census numbers to SIRUTA
# siruta: crosswalk between internal census area codes (MAPA) and official SIRUTA locality codes
# MAPA is used in the raw population DBFs; SIRUTA is needed for geographic merges across censuses
setwd(wd_data_raw)
setwd("./rpl_2002_microdate/s7_02/")
siruta<-read.dbf("s7_02.DBF") %>%
  select(MAPA,SIRUTA) %>%
  distinct()


# --- SIRUTA-to-SIRSUP Mapping ---
# siruta_mapping: converts 2002 locality codes (SIRUTA) to 2011 stable locality codes (SIRSUP) and county (jud)
# SIRSUP is the common geographic key used when merging 1992, 2002, and 2011 census records
setwd(wd_data_11_other)
siruta_mapping<-fread('siruta.CSV') %>%
  select(siruta,sirsup,jud)


# --- Load 2002 Common-Dwellings Population Files ---
# PPL* DBF files contain individual-level records for persons living in common (private) dwellings
# One file per geographic unit; combining them yields the full common-dwellings population
setwd(wd_data_raw)
setwd("./rpl_2002_microdate/POP02")



#do the PPl files
# List all DBF files starting with "PPL"
files <- list.files(pattern = "PPL.*\\.dbf$")

# Read all dbf files into a list
data_list <- lapply(files, read.dbf)

# Combine into one dataframe
data_2002_full<- bind_rows(data_list)

# --- Select and Rename Variables from Raw 2002 Census Codes ---
# Raw variable names (P12, P15, P16, etc.) follow the census form numbering; renaming to
# harmonised names shared across the 1992/2002/2011 scripts (see CENSUS VARIABLE GLOSSARY)
data_2002_full<-data_2002_full %>%
  # Drop unnamed overflow columns generated by the DBF reader
  select(-matches("X.|X$")) %>%
  select(MAPA=MAPA,
         CLAD,
         LOC,
         # GOSP=P00,
         NOP=PNR,
         # AA_SLR: year of last change of residence — used to classify residential movers
         AA_SLR=P12,
         # LOCN: locality of residence at the previous census (used to define movers vs stayers)
         LOCN=P13,
         LOCN_URB=P14,
         # JLOCN=P101,
         # AA: birth year — used to construct age and to form cell_id for cross-census matching
         AA=P16,
         # LL: sex (1 = male, 2 = female) — part of cell_id in sex-specific matching
         LL=P17,
         # ZZ: raw ethnicity code (12 = Roma); this is the key outcome variable
         ZZ=P18,
         SEX=P15,
         # SCA: 2002 education level code — mapped to the harmonised EDUC factor later
         SCA=P28,
         # SCU: 2002 schooling-in-progress field (different scale from SCA; used in 2011 harmonisation)
         SCU=P30,
         STATUT=P32,
         SECT=P35,
         # ET: ethnicity code duplicate used in figure scripts (mirrors ZZ)
         ET=P25,
         # LIM: mother-tongue code — used to construct ROMA_LANG (alternative Roma definition)
         LIM=P26,
         REL=P27,
         COPII=P22,
         # GOSP/GRUD/POPLOC/MOMLOC/SPLOC commented out: household-structure variables not needed
         # GRUD=P01,
         # POPLOC=P02,
         # MOMLOC=P03,
         OCUP=P34#,
         # SPLOC=P04
  ) %>%
  # Attach official SIRUTA code via MAPA crosswalk (s7_02.DBF loaded above)
  left_join(siruta %>% select(MAPA,SIRUTA)) %>% #maps a mapa to a siruta
  # Attach 2011-stable locality code (SIRSUP) and county (JUD) via the SIRUTA-to-SIRSUP mapping
  # SIRSUP is needed so that 2002 records can be spatially joined to 1992 and 2011 records
  left_join(siruta_mapping ,by=c("SIRUTA"="siruta")) %>% #this inputs the 2011 county - JUD (correct one)
  rename(SIRSUP=sirsup,
         JUD=jud)  %>%
  # LOCN codes 90 and 99 are special: 90 means "abroad county" (replace with county code JUD),
  # 99 means "unknown" — set to NA to avoid misclassifying mobility status
  mutate(LOCN=case_when(LOCN==90 ~ JUD,
                        LOCN==99 ~ NA,
                        TRUE ~ LOCN
  )) %>%
  # JLOCN: county of previous residence, defined only when LOCN is a valid county code (<=52)
  # Used to identify inter-county movers
  mutate(JLOCN=case_when(LOCN<=52 ~ LOCN,
                        TRUE ~ NA
  )) %>%
  # Tag all records as coming from the common-dwellings file (vs "full" stable population or "mig" migrants)
  mutate(source="common")



#save data
# Output: data_2002_common.csv — individual-level 2002 common-dwellings records with harmonised variable names
setwd(wd_data_02)
fwrite(data_2002_full,"data_2002_common.csv")

